### ISSUE TITLE
Double Write

### ISSUE THREAD

**Issue by semiversus** [xarantolus/stm32-flash-corruptor#1]
Wouldn't it also be possible to have two writes on the same address?

* Start with a erased section -> everything is ones (and the ECC too)
* Write a value e.g. 0x55 and the ECC bits are set accordingly
* Write another value e.g. 0xF0 on the same address. The ones will get set to zeros, but not vice versa. The ECC bits resulting in an invalid state.
* Reading the value will result in an ECC value (depends on the used values, which error will come up)

**Comment by xarantolus** [comment]
Doing two writes to the same address leads to a panic with the following `FLASH_SR` on the STM32L4R5ZI:

```
$ x/wx 0x40022010
0x40022010:     0x000000a8
```
It has the `PROGERR`, `PGAERR` and `PGSERR` bits set. The most relevant should be `PROGERR`: 
> Set by hardware when a double-word address to be programmed contains a value different from '0xFFFF FFFF' before programming, except if the data to write is '0x0000 0000'.


This is the code I used:
```rust

    // First of all, read all of the data to see if we get an interrupt
    // If yes, we are already in a corrupted state - nice!
    for i in 0..CORRUPT_RANGE {
        let addr = (APPROXIMATE_ADDRESS_TO_CORRUPT as usize) + i;

        let data = unsafe { core::ptr::read_volatile(addr as *const u8) };

        core::hint::black_box(data);
    }

    // If we reach this, there was no corruption in the aimed area
    let mut flash = Flash::new(peripherals.FLASH);
    let page_number = flash.address_to_page_number(APPROXIMATE_ADDRESS_TO_CORRUPT as u32);

    // First of all, we erase the page, as otherwise we can't write to it
    let mut flash_unlocked = flash.unlock().unwrap();
    flash_unlocked.erase_page(page_number).unwrap();

    // This gets us towards the time window...
    // Also this definitely isn't exactly cycles, but it does not really matter which unit of time we use
    for _ in 0..middle {
        core::hint::black_box(0);
    }

    // Now we write to actually corrupt the flash.
    // We basically hope that the watchdog setup was timed perfectly, so that we are in a phase of
    // flash writing where power must not be cut, and then we cut it
    flash_unlocked
        .write_dwords(
            APPROXIMATE_ADDRESS_TO_CORRUPT as *mut usize,
            &[0x55u64; CORRUPT_RANGE / core::mem::size_of::<u64>() + 1],
        )
        .unwrap();

        flash_unlocked
        .write_dwords(
            APPROXIMATE_ADDRESS_TO_CORRUPT as *mut usize,
            &[0xF0u64; CORRUPT_RANGE / core::mem::size_of::<u64>() + 1],
        )
        .unwrap();


    // If we reached this, we clearly didn't snipe early enough - after the next reset, we go lower
    peripherals.RTC.bkpr[3].write(|w| unsafe { w.bits(STATE_AFTER_WRITE) });
    set_blue_led(true);

    loop {

    }
```

I've been wondering about also producing single-bitflip errors, and if something like this but with timing shutdowns works it would be really cool :)

**Comment by semiversus** [comment]
Ah, I see. So the problem is that writing will not be done. Yes, then there will be no simpler solution than timed shutdown.
